### ISSUE TITLE
1.11 update

### ISSUE THREAD

**Issue by seema84** [Pluckerpluck/MultiInv#39]
`[09:53:13 ERROR]: Could not pass event PlayerGameModeChangeEvent to MultiInv v3.3.6
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.jar:git-
Spigot-d60de0a-54450b7]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.jar:git-Sp
igot-d60de0a-54450b7]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.jar:git-
Spigot-d60de0a-54450b7]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.jar:git-
Spigot-d60de0a-54450b7]
        at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.setGameMode(CraftPlayer.java:768) [spigot-1.11.j
ar:git-Spigot-d60de0a-54450b7]
        at com.sk89q.commandbook.PlayerComponent$Commands.gamemode(PlayerComponent.java:116) [commandbook-2.5-
SNAPSHOT.jar:2.5-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_102]
        at com.sk89q.minecraft.util.commands.CommandsManager.invokeMethod(CommandsManager.java:528) [worldedit
-bukkit-6.1.5-SNAPSHOT-dist.jar:?]
        at com.sk89q.minecraft.util.commands.CommandsManager.executeMethod(CommandsManager.java:516) [worldedi
t-bukkit-6.1.5-SNAPSHOT-dist.jar:?]
        at com.sk89q.minecraft.util.commands.CommandsManager.execute(CommandsManager.java:409) [worldedit-bukk
it-6.1.5-SNAPSHOT-dist.jar:?]
        at com.zachsthings.libcomponents.bukkit.BukkitComponent.onCommand(BukkitComponent.java:80) [commandboo
k-2.5-SNAPSHOT.jar:2.5-SNAPSHOT]
        at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:54) [worldedit-bukkit-
6.1.5-SNAPSHOT-dist.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.11.jar:git-Spigot
-d60de0a-54450b7]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:647) [spigot-1.11.jar:
git-Spigot-d60de0a-54450b7]
        at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1335) [spigot-1.
11.jar:git-Spigot-d60de0a-54450b7]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1170) [spigot-1.11.jar:git-S
pigot-d60de0a-54450b7]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.11.jar:git-Spi
got-d60de0a-54450b7]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.11.jar:git-Spig
ot-d60de0a-54450b7]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.jar:git-Spigo
t-d60de0a-54450b7]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_102]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_102]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.jar:git-Spigot-d60de0a-5445
0b7]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.11.jar:git-Spig
ot-d60de0a-54450b7]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spig
ot-d60de0a-54450b7]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.jar:git-Spig
ot-d60de0a-54450b7]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Sp
igot-d60de0a-54450b7]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_102]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_10_R1/NBTBase
        at uk.co.tggl.pluckerpluck.multiinv.inventory.MIItemStack.<init>(MIItemStack.java:64) ~[?:?]
        at uk.co.tggl.pluckerpluck.multiinv.inventory.MIInventory.<init>(MIInventory.java:34) ~[?:?]
        at uk.co.tggl.pluckerpluck.multiinv.player.MIPlayer.saveInventory(MIPlayer.java:97) ~[?:?]
        at uk.co.tggl.pluckerpluck.multiinv.listener.MIPlayerListener.onPlayerGameModeChange(MIPlayerListener.
java:485) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_102]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.jar:git-
Spigot-d60de0a-54450b7]
        ... 29 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_10_R1.NBTBase
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot-1.11.jar:git
-Spigot-d60de0a-54450b7]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.11.jar:git
-Spigot-d60de0a-54450b7]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_102]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_102]
        at uk.co.tggl.pluckerpluck.multiinv.inventory.MIItemStack.<init>(MIItemStack.java:64) ~[?:?]
        at uk.co.tggl.pluckerpluck.multiinv.inventory.MIInventory.<init>(MIInventory.java:34) ~[?:?]
        at uk.co.tggl.pluckerpluck.multiinv.player.MIPlayer.saveInventory(MIPlayer.java:97) ~[?:?]
        at uk.co.tggl.pluckerpluck.multiinv.listener.MIPlayerListener.onPlayerGameModeChange(MIPlayerListener.
java:485) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_102]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.jar:git-
Spigot-d60de0a-54450b7]
        ... 29 more`

**Comment by Tux2** [comment]
Wrong version of TuxTwoLib

**Comment by seema84** [comment]
its was befor you release the new tuxtwolib version but yes its fixed
