### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by IIMrRamII** [Pluckerpluck/MultiInv#42]
Could not pass event PlayerTeleportEvent to MultiInv v3.3.8
org.bukkit.event.EventException
	at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:118) ~[?:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at me.incomprehendable.dev.pwp.transparentlisteners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:28) ~[?:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:444) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.teleport(CraftEntity.java:226) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at iimrramii.login.Main.SendToLobby(Main.java:162) ~[?:?]
	at iimrramii.login.Main.onLogin(Main.java:173) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:116) ~[?:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at me.incomprehendable.dev.pwp.transparentlisteners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:28) ~[?:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at fr.xephi.authme.service.BukkitService.callEvent(BukkitService.java:264) ~[?:?]
	at fr.xephi.authme.process.login.ProcessSyncPlayerLogin.processPlayerLogin(ProcessSyncPlayerLogin.java:102) ~[?:?]
	at fr.xephi.authme.process.SyncProcessManager.lambda$processSyncPlayerLogin$3(SyncProcessManager.java:51) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NoClassDefFoundError: Tux2/TuxTwoLib/TuxTwoPlayerHead
	at uk.co.tggl.pluckerpluck.multiinv.inventory.MIItemStack.getItemMetaSerialized(MIItemStack.java:674) ~[?:?]
	at uk.co.tggl.pluckerpluck.multiinv.inventory.MIItemStack.<init>(MIItemStack.java:84) ~[?:?]
	at uk.co.tggl.pluckerpluck.multiinv.inventory.MIInventory.<init>(MIInventory.java:37) ~[?:?]
	at uk.co.tggl.pluckerpluck.multiinv.player.MIPlayer.saveAll(MIPlayer.java:119) ~[?:?]
	at uk.co.tggl.pluckerpluck.multiinv.listener.MIPlayerListener.savePlayerState(MIPlayerListener.java:507) ~[?:?]
	at uk.co.tggl.pluckerpluck.multiinv.listener.MIPlayerListener.onPlayerTeleport(MIPlayerListener.java:419) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor389.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:116) ~[?:?]
	... 27 more

My server version: 1.8.8
But i can't find Tux for 1.8.8 i'm using
https://dev.bukkit.org/projects/tuxtwolib/files/881435
And i know there is my plugin but i think the problem is from Tux

**Comment by IIMrRamII** [comment]
i think this is the problem
Caused by: java.lang.NoClassDefFoundError: Tux2/TuxTwoLib/TuxTwoPlayerHead

**Comment by Tux2** [comment]
So, the issue is because the version of MultiInv you are using is only for 1.11 and up due to compatibility reasons. The last version to support Spigot/Bukkit version 1.8.8 is version 3.3.6: https://dev.bukkit.org/projects/multiinv/files/911287

The version of TuxTwoLib you have is correct for your server version however.
